Watching for file changes with StatReloader
Attempting to connect to API
Attempting to connect to API
Attempting to connect to API
/Users/bapmarine/p12_django_postgres/contracts/permissions.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/contracts/permissions.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/permissions.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/permissions.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/permissions.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/account/contracts/
Traceback (most recent call last):
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/permissions.py", line 72, in has_permission
    return self.op1.has_permission(request, view) or self.op2.has_permission(
  File "/Users/bapmarine/p12_django_postgres/contracts/permissions.py", line 10, in has_permission
    contract = Contract.objects.get(id=view.kwargs["pk"])
KeyError: 'pk'
/Users/bapmarine/p12_django_postgres/contracts/permissions.py changed, reloading.
Watching for file changes with StatReloader
Attempting to connect to API
Attempting to connect to API
Attempting to connect to API
Not Found: /favicon.ico
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Internal Server Error: /api/account/clients/
Traceback (most recent call last):
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/Users/bapmarine/p12_django_postgres/clients/views.py", line 24, in get_queryset
    contracts = Contract.objects.filter(support_team=self.request.user)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1377, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1187, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1677, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'support_team' into field. Choices are: amount, client, client_id, content, date, event_contract, id, status, title
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/account/clients/
Traceback (most recent call last):
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/Users/bapmarine/p12_django_postgres/clients/views.py", line 25, in get_queryset
    contracts = Contract.objects.filter(support_team=self.request.user)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1377, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1187, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1677, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'support_team' into field. Choices are: amount, client, client_id, content, date, event_contract, id, status, title
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/account/clients/
Traceback (most recent call last):
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/Users/bapmarine/p12_django_postgres/clients/views.py", line 25, in get_queryset
    contracts = Contract.objects.filter(support_team=self.request.user)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1377, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1187, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1677, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'support_team' into field. Choices are: amount, client, client_id, content, date, event_contract, id, status, title
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/account/clients/
Traceback (most recent call last):
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/Users/bapmarine/p12_django_postgres/clients/views.py", line 26, in get_queryset
    contracts = Contract.objects.filter(support_team=self.request.user)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1377, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1187, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Users/bapmarine/p12_django_postgres/env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1677, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'support_team' into field. Choices are: amount, client, client_id, content, date, event_contract, id, status, title
Not Found: /favicon.ico
/Users/bapmarine/p12_django_postgres/contracts/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/contracts/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
/Users/bapmarine/p12_django_postgres/clients/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/clients/permissions.py changed, reloading.
Watching for file changes with StatReloader
/Users/bapmarine/p12_django_postgres/contracts/views.py changed, reloading.
Watching for file changes with StatReloader
